version: '3.8'

services:
  app:
    image: ghcr.io/growlf/toolbox:testing
    stdin_open: true
    tty: true
    command: ["/bin/zsh"]
    restart: unless-stopped  # Ensures it restarts on failures
    ports:
      - "8080:8080"  # Change based on your application needs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data  # Persistent data storage
    networks:
      - toolbox_network

networks:
  toolbox_network:
    driver: bridge  # Portainer prefers explicit network settings

volumes:
  portainer_data:
    driver: local
