version: '3.8'

services:
  app:
    image: ghcr.io/growlf/toolbox:testing
    stdin_open: true
    tty: true
    command: ["/bin/zsh"]
    restart: unless-stopped
    ports:
      - "8080:8080"  # Adjust if needed
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data  # Persistent data storage
    networks:
      - toolbox_network

networks:
  toolbox_network:
    driver: bridge

volumes:
  portainer_data:
    driver: local
