services:
  app:
    image: my_toolbox_image  # Use local image instead
    stdin_open: true
    tty: true
    command: ["/bin/zsh"]
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - toolbox_network  # Ensure this network is properly defined

networks:
  toolbox_network:
    driver: bridge  # Define the missing network

volumes:
  portainer_data:
    driver: local  # Define volume for persistent data
